# Generated by Django 3.0.6 on 2020-06-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Imagen Original', max_length=200),
        ),
        migrations.AlterField(
            model_name='post1',
            name='title',
            field=models.CharField(blank=True, default='Setup', max_length=200, null=True),
        ),
    ]
